CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE quiz(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    unique_key TEXT DEFAULT uuid_generate_v4() UNIQUE,
    title TEXT NOT NULL, 
    description TEXT NOT NULL,
    -- category TEXT NOT NULL,
    private BOOLEAN
);