CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TYPE categories AS ENUM (
    'Animal',
    'Art',
    'Food',
    'Geography',
    'History',
    'Literature',
    'Movie/Tv',
    'Music',
    'Personal',
    'Political',
    'Random',
    'Science',
    'Sports',
    'Video-Games'
);
CREATE TABLE quiz(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    unique_key TEXT DEFAULT uuid_generate_v4() UNIQUE,
    title TEXT NOT NULL, 
    description TEXT NOT NULL,
    category categories NOT NULL,
    private BOOLEAN
);