CREATE TABLE questions(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    quiz_id TEXT 
        REFERENCES quiz(unique_key) ON DELETE CASCADE NOT NULL,
    question TEXT NOT NULL,
    answers TEXT[4] NOT NULL,
    correct TEXT NOT NULL
);